cargo-features = ["edition2024"]

[package]
name = "fragment"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["dylib"]

[dependencies]
spirv-std = { version = "0.9" }
koi-gpu = { path = "../../koi/gpu" }

[lints]
workspace = true