[workspace]
resolver = "2"
members = [
    "game",
    "koi",
    "shaders/imgui",
    "shaders/gradient",
]

[workspace.lints.rust]
unexpected_cfgs = { level = "allow", check-cfg = ['cfg(target_arch, values("spirv"))', 'cfg(spirv, values("vertex", "fragment", "compute"))'] }
