cargo-features = ["edition2024"]

[package]
name = "koi-gpu"
version = "0.1.0"
edition = "2024"

[dependencies]
spirv-std = { version = "0.9" }

[target.'cfg(not(target_arch = "spirv"))'.dependencies]
bytemuck = "1.22.0"

[lints]
workspace = true