[package]
name = "koi"
version = "0.1.0"
edition = "2024"

[dependencies]
ash = "0.38.0"
gpu-allocator = "0.27.0"
image = "0.25.5"
log = "0.4"
winit = "0.30.9"

[features]
default = ["vulkan", "debug"]
debug = []
vulkan = []
directx = []
