cargo-features = ["edition2024"]

[package]
name = "gradient"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["dylib"]

[dependencies]
spirv-std = { version = "0.9" }

[lints]
workspace = true